# Bronze Layer
### Purpose:
Load Raw Data

Validate Raw Data

Data Info & Description

Store Raw Data in Bronze Layer

Import Libraries

In [1]:
import pandas as pd

Upload Dataset

In [2]:
from google.colab import files

uploaded = files.upload()

Saving Modified_Daily_Data.csv to Modified_Daily_Data.csv

Read Dataset

In [3]:
df = pd.read_csv("Modified_Daily_Data.csv")

Dataset Shape

In [4]:
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Rows    : 821250
Columns : 8

Column Names

In [5]:
for col in df.columns:
    print(col)

Date
Branch
Drug_Name
Sales_Quantity
Unit_Price
Unit_Cost
Expired_Quantity
Damaged_Quantity

Data Types

In [6]:
df.dtypes

Date                 object
Branch               object
Drug_Name            object
Sales_Quantity        int64
Unit_Price          float64
Unit_Cost           float64
Expired_Quantity      int64
Damaged_Quantity      int64
dtype: object

Missing Value

In [7]:
df.isnull().sum()

Date                0
Branch              0
Drug_Name           0
Sales_Quantity      0
Unit_Price          0
Unit_Cost           0
Expired_Quantity    0
Damaged_Quantity    0
dtype: int64

Duplicate Records

In [8]:
df.duplicated().sum()

np.int64(0)

Dataset Information

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 821250 entries, 0 to 821249
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Date              821250 non-null  object
 1   Branch            821250 non-null  object
 2   Drug_Name         821250 non-null  object
 3   Sales_Quantity    821250 non-null  int64
 4   Unit_Price        821250 non-null  float64
 5   Unit_Cost         821250 non-null  float64
 6   Expired_Quantity  821250 non-null  int64
 7   Damaged_Quantity  821250 non-null  int64
dtypes: float64(2), int64(3), object(3)
memory usage: 50.1+ MB

 Statistical Description

In [10]:
df.describe()

,Sales_Quantity,Unit_Price,Unit_Cost,Expired_Quantity,Damaged_Quantity
count,821250.000000,821250.000000,821250.000000,821250.000000,821250.000000
mean,39.410088,83.184263,58.651310,0.320597,0.267714
std,104.700321,42.442928,31.666353,0.889327,2.202122
min,1.000000,10.000000,5.040000,0.000000,0.000000
25%,10.000000,46.580000,32.150000,0.000000,0.000000
50%,16.000000,82.770000,57.200000,0.000000,0.000000
75%,22.000000,119.020000,82.490000,0.000000,0.000000
max,3652.000000,173.930000,198.030000,16.000000,128.000000

Create Bronze Layer

In [11]:
from google.colab import drive

drive.mount('/content/drive')

df.to_csv(
    "/content/drive/MyDrive/Depi Grad Project/Data/Bronze/bronze_salesss.csv",
    index=False
)

Mounted at /content/drive